kind: Pod
apiVersion: v1
metadata:
  name: my-pod
spec:
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: pv-claim
  containers:
    - name: my-container
      image: bitnami/nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: my-storage
