apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myqpp
    type: front-end
spec:
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        type: frontend
    spec:
      containers:
        - image: nginx
          name: nginx-container
